spring:
  application:
    name: opptaksystem
  
  # GraphQL konfigurasjon
  graphql:
    path: /graphql
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
    
  # Database konfigurasjon - starter med H2 in-memory for enkel testing
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Flyway for database migrering
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JOOQ konfigurasjon
  jooq:
    sql-dialect: H2
  
  # H2 Console for å se databasen
  h2:
    console:
      enabled: true
      path: /h2-console

# Server port
server:
  port: 80
  address: 0.0.0.0